CREATE TABLE IF NOT EXISTS ecommerce.customer(
CUS_ID INT NOT NULL auto_increment,
CUS_NAME VARCHAR(20) NOT NULL,
CUS_PHONE VARCHAR(10) NOT NULL,
CUS_CITY varchar(30) NOT NULL,
CUS_GENDER CHAR,
PRIMARY KEY (CUS_ID));